version: "3.8"

services:
  zabbix-web:
    image: zabbix/zabbix-web-nginx-mysql:latest
    container_name: zabbix-web
    environment:
      DB_SERVER_HOST: mysql
      MYSQL_USER: zabbix
      MYSQL_PASSWORD: zabbix_pass
      MYSQL_DATABASE: zabbix
      ZBX_SERVER_HOST: zabbix-server
      PHP_TZ: Europe/Paris
    depends_on:
      - mysql
      - zabbix-server
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.zabbix.rule=Host(`zabbix.localhost`)"
      - "traefik.http.services.zabbix.loadbalancer.server.port=8080"
    networks:
      - zabbix-net
      - traefik

  mysql:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: zabbix
      MYSQL_USER: zabbix
      MYSQL_PASSWORD: zabbix_pass
      MYSQL_ROOT_PASSWORD: root_pass
    command: --log-bin-trust-function-creators=1
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - zabbix-net

  zabbix-server:
    image: zabbix/zabbix-server-mysql:alpine-6.0-latest
    environment:
      DB_SERVER_HOST: mysql
      MYSQL_USER: zabbix
      MYSQL_PASSWORD: zabbix_pass
    depends_on:
      - mysql
    networks:
      - zabbix-net

volumes:
  mysql_data:

networks:
  zabbix-net:
  traefik:
    external: true

